# NicoCache用デフォルト設定値定義ファイル
#
# このファイルは変更しないでください。
# 設定を変更する場合はインストールフォルダのconfig.propertiesに
# 設定を記述してください。

# NicoCacheの待ち受けポート。
listenPort=8080

# 併用するプロキシのホスト名かIPアドレス。空にすると併用なし。
proxyHost=

# 併用するプロキシの待ち受けポート。
proxyPort=8081

# SSL通信でもセカンダリプロキシを通すかどうか。(true/false)
proxySSL=true

# キャッシュファイル名に動画のタイトルを付けるかどうか。(true/false)
title=true

# 途中でブラウザを閉じた動画を再度見たときに
# 残りの部分からDLを再開するかどうか。(true/false)
resumeDownload=true

# キャッシュを参照した際にタイムスタンプを更新するか。(true/false)
touchCache=true

# ブラウザからのデータ待ちうけタイムアウト。(ミリ秒)
readTimeout=600000

# ファイル名に使う文字セット。空にするとUnicode。(Javaの文字セット名)
fileNameCharset=

# (実験的機能) HTTPヘッダに非ASCII文字を含めるブラウザでも
# 動作するように試みる。(true/false)
useWorkaroundForEncoding=false

# (実験的機能) NicoCache終了時に通信先サーバとの通信を
# 早く切断するように試みる。(true/false)
useWorkaroundFastFinalize=false
