# NicoCache_nl 設定ファイル(文字コード判定用なのでこの行は削除しないこと)

# TLSへのMitM処理を有効にするか [S]
#   有効にするとmitmHostPortRegexにマッチした処理対象のホストとのHTTPS通信を
#   NicoCache_nl内で一旦終端して，書き換えなどの処理を行ったうえで，
#   certs/site.cerの証明書でHTTPSに戻してブラウザに送り出します．
#   有効にした場合，証明書の検査を行い異常が発見された場合には動作を停止します．
enableMitm=true

# TLSへのMitMを有効にする対象ホスト [S]
#   対象のホストとポートを ホスト あるいは ホスト:ポート の形式でスペース区切りで列挙します．
#   *はワイルドカードを意味します．ホスト部のワイルドカードは.にはマッチしません．
#   ポート部を省略した場合は443番ポートのみが対象となります．
#   対象のドメインを増やした場合には証明書を作りなおす必要があります．
#   (証明書を再生成した後は要再起動)
#   See NicoCacheCA.jar and certificate-targets.txt
mitmHostPort=*.nicovideo.jp *.ce.nicovideo.jp *.sl.nicovideo.jp *.domand.nicovideo.jp:* *.sv.nicovideo.jp *.nicoad.nicovideo.jp *.seiga.nicovideo.jp *.smilevideo.jp *.nimg.jp *.cdn.nimg.jp *.video.nimg.jp *.dmc.nico:* *.nvcomment.nicovideo.jp
