# 値を変更する場合は config.properties に追加してください
# これらの値は swfConvert04 以降であれば動的に変更が反映されます([S]は除く)

# 同時ダウンロード数 (1～5)
#   複数のfetch要求に対して同時にダウンロード可能な数を指定する。
#   回線が細い場合は少ない数を指定した方が良いかも。
#   ただし、連続アクセス規制時の待ち時間も数に含まれるので注意。
#   非プレミアム会員は同時に開けるタブの数に基づき上限2に制限。
movieFetchMax=1

# リトライ回数 (0～9)
#   鯖エラー等の様々な要因でfetchに失敗した時にリトライする回数を指定する。
#   リトライ回数を超えてfetchに失敗した場合も取得動画リストには残るので、
#   後からfetchに失敗した動画を直接見ることは出来る。
movieFetchRetry=5

# エコノミー動画をfetch予約 (true/false)
#   通常はエコノミー動画に対してもfetchを実行するが、この値をtrueにすると
#   エコノミー動画の場合は直ぐにfetchを実行せずに、翌日のエコノミー時間帯明け
#   (午前2時～5時までのランダムな時間)にfetchを実行するように予約する。
#   予約が実行される前にNicoCache_nlを再起動すると予約が消えてしまうので注意。
movieFetchNoEconomy=false

# 不完全キャッシュを更新 (true/false)
#   この値がtrueなら、エコノミーキャッシュや一時ファイルを通常キャッシュに
#   更新するためのfetchを午前2時～5時の間に実行する。(updatelow.rb相当)
#   この機能はfetch予約の応用なので、一度でもfetchを実行しないと機能しない。
#   また、動画タイトルの末尾が "削除]" の場合は更新しない。(totalRename互換)
#   対象の動画が削除される等で取得できないと毎日fetch実行されるので注意。
movieFetchUpdateCache=false

# ファイル保存時の文字セット [S]
#   ファイル保存時の文字セットを文字列で指定する。(Javaで利用可能なもの)
#   複数のOSで利用するなら UTF-8 を指定するのが無難。
#   何も指定しない場合はシステムのデフォルト文字セットを使用する。
movieFetchCharset=

# 自動的に視聴済 (true/false)
#   この値がtrueなら、watchページで視聴した動画IDを自動的に視聴済にして
#   取得動画リストから削除する。なお、本機能はリクエスト段階で実行するので、
#   何らかの原因でwatchページが表示出来なくてもリストから削除されるので注意。
#   また、URLだけで判断するのでチャンネル動画等のスレッドIDでは機能しない。
movieFetchAutoWatched=false

# totalRenameの削除履歴情報を使用 (true/false)
#   この値がtrueなら、totalRename v0.7以降の削除履歴情報を参照して、過去に
#   削除した動画や無視登録した動画のfetchを行わない。
#   totalRenameを併用しない場合はtrueを指定しても意味が無い。
movieFetchUseRemoveInfo=false

# セッションの取得 (数値文字列)
#   指定したユーザーIDのセッションを取得して次回以降のfetchで利用する。
#   この値を空文字列にすると、次回fetch時に取得したセッションを破棄する。
movieFetchCaptureUserID=

# プレミアム待ち時間 (秒)
#   プレミアムアカウントは帯域制限が無いので、連続アクセス規制になりやすい。
#   そのため、プレミアムアカウントの場合はfetch終了時に最大で指定秒数までの
#   ランダムな待ち時間を入れる。一般アカウントの場合は関係無い。
movieFetchPremiumWait=30

# 予約時待ち時間 (秒)
#   fetch時にエコノミーだった場合、movieFetchNoEconomy=trueなら
#   ごく短時間で処理が終了するため連続アクセス規制になりやすい。
#   そのため、予約した場合は最大で指定秒数までのランダムな待ち時間を入れる。
movieFetchReservedWait=30

# dmcの通信にwell-knownポートのsession APIを利用
#   この値がtrueなら、is_well_known_portがtrueのsession apiを使用する。
#   dmc動画のfetchに失敗する場合はtrueにすると動くようになるかも。
movieFetchUseWellKnownPort=false

# 再生時間に合わせて取得速度を調整
#   この機能が有効な場合、動画の取得にかかった時間が再生時間の
#   movieFetchPlaySpeedScaleよりも短い場合に待ち時間を入れる。
#   0:無効、1:有効、2:チャンネル動画のみ有効
movieFetchPlaySpeed=0

# 再生時間にかける係数
movieFetchPlaySpeedScale=1.0

# 非ログイン状態でのfetchを有効化
#   この値がtrueなら、ログインしていない状態でもfetchできるようにする。
movieFetchAllowGuest=false

# デバッグモード
#   この値がtrueなら、デバッグログを出力する。
movieFetchDebug=false

# 詳細なデバッグモード
#   この値がtrueなら、より詳細なデバッグログを出力する。
movieFetchDebug2=false
